import type { Question } from "../../shared/game";

const entries: Array<[string, string, number, string]> = [
  ["everest", "How tall is Mount Everest?", 8849, "meters"],
  ["bones", "How many bones are in an adult human body?", 206, "bones"],
  ["moon", "How far is the Moon from Earth?", 384400, "km"],
  ["light", "How fast does light travel?", 299792, "km/s"],
  ["eiffel", "How tall is the Eiffel Tower?", 330, "meters"],
  ["ocean", "How deep is the Mariana Trench?", 10984, "meters"],
  ["earth", "What is Earth’s circumference at the equator?", 40075, "km"],
  ["heart", "How many times does a heart beat in a day?", 100000, "beats"],
  ["mars", "How far is Mars from Earth on average?", 225000000, "km"],
  ["amazon", "How long is the Amazon River?", 6400, "km"],
  ["pyramid", "How tall was the Great Pyramid originally?", 146, "meters"],
  ["sahara", "How large is the Sahara Desert?", 9200000, "km²"],
  ["jupiter", "How many Earths could fit inside Jupiter?", 1321, "Earths"],
  ["whale", "How long can a blue whale grow?", 30, "meters"],
  ["speed", "How fast can a cheetah run?", 110, "km/h"],
  ["age", "How old is Earth?", 4540000000, "years"],
  ["water", "What is the boiling point of water at sea level?", 100, "°C"],
  ["paris", "How tall is the Statue of Liberty?", 93, "meters"],
  ["gold", "What is the atomic number of gold?", 79, ""],
  ["population", "How many people live in the world?", 8100000000, "people"],
  ["sound", "How fast does sound travel in air?", 343, "m/s"],
  ["volcano", "How tall is Mauna Kea from base to peak?", 10210, "meters"],
  ["rings", "How many rings are on the Olympic symbol?", 5, "rings"],
  ["days", "How many days are in a leap year?", 366, "days"],
  ["giraffe", "How tall can a giraffe grow?", 5.5, "meters"],
  ["greatwall", "How long is the Great Wall of China?", 21196, "km"],
  ["neptune", "How long is one year on Neptune?", 165, "Earth years"],
  ["sydney", "How tall is the Sydney Harbour Bridge?", 134, "meters"],
  ["ant", "How much can an ant lift relative to its body weight?", 50, "times"],
  ["shark", "How many teeth can a great white shark have at once?", 300, "teeth"],
  ["sun-distance", "How far is the Sun from Earth on average?", 149600000, "km"],
  ["sun-diameter", "What is the Sun's diameter?", 1392700, "km"],
  ["moon-diameter", "What is the Moon's diameter?", 3475, "km"],
  ["earth-diameter", "What is Earth's diameter?", 12742, "km"],
  ["jupiter-diameter", "What is Jupiter's diameter?", 139820, "km"],
  ["saturn-diameter", "What is Saturn's diameter?", 116460, "km"],
  ["mercury-year", "How many Earth days are in a year on Mercury?", 88, "days"],
  ["venus-year", "How many Earth days are in a year on Venus?", 225, "days"],
  ["mars-year", "How many Earth days are in a year on Mars?", 687, "days"],
  ["jupiter-year", "How many Earth years are in a year on Jupiter?", 11.86, "years"],
  ["saturn-year", "How many Earth years are in a year on Saturn?", 29.5, "years"],
  ["uranus-year", "How many Earth years are in a year on Uranus?", 84, "years"],
  ["pluto-year", "How many Earth years are in a year on Pluto?", 248, "years"],
  ["moon-gravity", "What percentage of Earth's gravity does the Moon have?", 16.5, "%"],
  ["earth-tilt", "What is Earth's axial tilt?", 23.4, "degrees"],
  ["iss-speed", "How fast does the International Space Station travel?", 27600, "km/h"],
  ["iss-altitude", "How high above Earth does the International Space Station orbit?", 400, "km"],
  ["hubble-altitude", "How high above Earth does the Hubble Space Telescope orbit?", 540, "km"],
  ["milky-way-stars", "About how many stars are in the Milky Way?", 100000000000, "stars"],
  ["milky-way-width", "How wide is the Milky Way?", 100000, "light years"],
  ["andromeda-distance", "How far away is the Andromeda Galaxy?", 2500000, "light years"],
  ["solar-system-age", "How old is the Solar System?", 4600000000, "years"],
  ["light-year", "How far does light travel in one year?", 9461000000000, "km"],
  ["human-cells", "About how many cells are in the human body?", 37000000000000, "cells"],
  ["dna-length", "How much DNA is in one human cell if stretched out?", 2, "meters"],
  ["blood-volume", "How much blood does an average adult have?", 5, "liters"],
  ["skin-area", "What is the surface area of an average adult's skin?", 2, "m²"],
  ["brain-weight", "How much does an average adult brain weigh?", 1.4, "kg"],
  ["lungs", "How many lungs does a typical human have?", 2, "lungs"],
  ["teeth-adult", "How many teeth does a typical adult have?", 32, "teeth"],
  ["teeth-baby", "How many teeth does a typical child have?", 20, "teeth"],
  ["chromosomes", "How many chromosomes are in a typical human cell?", 46, "chromosomes"],
  ["body-water", "What percentage of an adult human body is water?", 60, "%"],
  ["blink", "How many times does a person blink in a day on average?", 15000, "blinks"],
  ["sneeze", "How fast can a sneeze travel?", 160, "km/h"],
  ["tongue", "How many taste buds does a typical adult have?", 10000, "taste buds"],
  ["elephant-weight", "How much can an African elephant weigh?", 6000, "kg"],
  ["elephant-gestation", "How long is an elephant's pregnancy?", 22, "months"],
  ["ostrich-speed", "How fast can an ostrich run?", 70, "km/h"],
  ["peregrine", "How fast can a peregrine falcon dive?", 320, "km/h"],
  ["sloth", "How many hours can a sloth sleep in a day?", 20, "hours"],
  ["bee-wings", "How many times per second can a bee beat its wings?", 230, "beats"],
  ["octopus-hearts", "How many hearts does an octopus have?", 3, "hearts"],
  ["octopus-arms", "How many arms does an octopus have?", 8, "arms"],
  ["penguin-depth", "How deep can an emperor penguin dive?", 500, "meters"],
  ["kangaroo-jump", "How far can a red kangaroo jump in one leap?", 9, "meters"],
  ["frog-jump", "How far can a flea jump relative to its body length?", 200, "times"],
  ["snail-speed", "How fast can a garden snail move?", 0.05, "km/h"],
  ["turtle-age", "How old can a giant tortoise live?", 150, "years"],
  ["tree-height", "How tall can a coast redwood grow?", 115, "meters"],
  ["bamboo-growth", "How much can bamboo grow in one day?", 91, "cm"],
  ["rainforest", "What percentage of Earth's land is covered by tropical rainforest?", 6, "%"],
  ["water-earth", "What percentage of Earth's surface is covered by water?", 71, "%"],
  ["ocean-earth", "What percentage of Earth's water is in the oceans?", 97, "%"],
  ["pacific", "How large is the Pacific Ocean?", 165250000, "km²"],
  ["atlantic", "How large is the Atlantic Ocean?", 106460000, "km²"],
  ["indian-ocean", "How large is the Indian Ocean?", 70560000, "km²"],
  ["arctic-ocean", "How large is the Arctic Ocean?", 15558000, "km²"],
  ["nile", "How long is the Nile River?", 6650, "km"],
  ["mississippi", "How long is the Mississippi River?", 6275, "km"],
  ["yangtze", "How long is the Yangtze River?", 6300, "km"],
  ["congo", "How long is the Congo River?", 4700, "km"],
  ["lake-superior", "What is the surface area of Lake Superior?", 82100, "km²"],
  ["baikal-depth", "How deep is Lake Baikal at its deepest point?", 1642, "meters"],
  ["africa", "How large is Africa?", 30370000, "km²"],
  ["asia", "How large is Asia?", 44580000, "km²"],
  ["europe", "How large is Europe?", 10180000, "km²"],
  ["antarctica", "How large is Antarctica?", 14200000, "km²"],
  ["australia", "How large is Australia?", 7692000, "km²"],
  ["canada", "How large is Canada?", 9985000, "km²"],
  ["india", "How large is India?", 3287000, "km²"],
  ["usa", "How large is the United States?", 9834000, "km²"],
  ["brazil", "How large is Brazil?", 8516000, "km²"],
  ["china", "How large is China?", 9597000, "km²"],
  ["tokyo-population", "About how many people live in greater Tokyo?", 37000000, "people"],
  ["london-population", "About how many people live in London?", 9000000, "people"],
  ["new-york-population", "About how many people live in New York City?", 8300000, "people"],
  ["burj-khalifa", "How tall is the Burj Khalifa?", 828, "meters"],
  ["empire-state", "How tall is the Empire State Building including its antenna?", 443, "meters"],
  ["big-ben", "How tall is the Elizabeth Tower, home to Big Ben?", 96, "meters"],
  ["colosseum", "How old is the Colosseum?", 1950, "years"],
  ["taj-mahal", "How old is the Taj Mahal?", 373, "years"],
  ["pisa", "How tall is the Leaning Tower of Pisa?", 57, "meters"],
  ["panama-canal", "How long is the Panama Canal?", 82, "km"],
  ["channel-tunnel", "How long is the Channel Tunnel?", 50.5, "km"],
  ["golden-gate", "How long is the Golden Gate Bridge?", 2737, "meters"],
  ["longest-flight", "How long is the world's longest scheduled passenger flight?", 15300, "km"],
  ["circumnavigation", "How long is a trip around Earth at the equator?", 40075, "km"],
  ["mile-km", "How many kilometers are in one mile?", 1.609, "km"],
  ["marathon", "How long is a marathon?", 42.195, "km"],
  ["football-field", "How long is an American football field including end zones?", 120, "yards"],
  ["tennis-court", "How long is a tennis court?", 23.77, "meters"],
  ["basketball-rim", "How high is a basketball rim?", 3.05, "meters"],
  ["soccer-match", "How many minutes are in a regulation soccer match?", 90, "minutes"],
  ["baseball-innings", "How many innings are in a regulation baseball game?", 9, "innings"],
  ["chess-squares", "How many squares are on a chessboard?", 64, "squares"],
  ["cards", "How many cards are in a standard deck without jokers?", 52, "cards"],
  ["dice-sides", "How many sides does a standard die have?", 6, "sides"],
  ["piano-keys", "How many keys are on a standard piano?", 88, "keys"],
  ["guitar-strings", "How many strings does a standard guitar have?", 6, "strings"],
  ["speed-record", "What is the land speed record for a wheeled vehicle?", 1228, "km/h"],
  ["human-speed", "What is Usain Bolt's 100-meter world record?", 9.58, "seconds"],
  ["olympic-pool", "How long is an Olympic swimming pool?", 50, "meters"],
  ["mountain-k2", "How tall is K2?", 8611, "meters"],
  ["kilimanjaro", "How tall is Mount Kilimanjaro?", 5895, "meters"],
  ["fuji", "How tall is Mount Fuji?", 3776, "meters"],
  ["denali", "How tall is Denali?", 6190, "meters"],
  ["victoria-falls", "How tall is Victoria Falls?", 108, "meters"],
  ["niagara-falls", "How tall is Niagara Falls?", 51, "meters"],
  ["machu-picchu", "How high above sea level is Machu Picchu?", 2430, "meters"],
  ["everest-climbers", "About how many people have reached the summit of Mount Everest?", 12000, "people"],
];

export const QUESTIONS: Question[] = entries.map(
  ([id, question, answer, unit]) => ({
    id,
    question,
    answer,
    unit,
  }),
);
